### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by StarSpark** [Jlanglang/TreeRecyclerView#11]
java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object[] java.util.Collection.toArray()' on a null object reference
        at java.util.ArrayList.addAll(ArrayList.java:228)
        at com.baozi.treerecyclerview.item.TreeItemGroup.onExpand(TreeItemGroup.java:68)
        at com.baozi.treerecyclerview.item.TreeItemGroup.setExpand(TreeItemGroup.java:45)
        at com.baozi.treerecyclerview.adpater.TreeRecyclerAdapter$1.onClick(TreeRecyclerAdapter.java:57)
        at android.view.View.performClick(View.java:4790)
        at android.view.View$PerformClick.run(View.java:19924)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5418)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1037)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

我在使用三级列表的时候，点击偶尔会报错，我在源码处判空，也没得到解决，还是会报错！求解决！！！

**Comment by Jlanglang** [comment]
@StarSpark 你好，我大概知道问题了。是因为
 /**
     * 获得所有展开的childs,包括子item的childs
     *
     * @return
     */
    @Nullable
    private List<TreeItem> getExpandChild() {
//        if (getChild() == null) {
//            return null;
//        }
        return ItemHelperFactory.getChildItemsWithType(this, TreeRecyclerType.SHOW_EXPAND);
    }


   /**
     * 展开
     */
    protected void onExpand() {
        isExpand = true;
        ItemManager itemManager = getItemManager();
        if (itemManager != null) {
            int itemPosition = itemManager.getItemPosition(this);
            List datas = itemManager.getAdapter().getDatas();
            datas.addAll(itemPosition + 1, getExpandChild());//这里add不能add一个null。所以报错了。
            itemManager.notifyDataChanged();
        }
    }

**Comment by StarSpark** [comment]
@Jlanglang ,你好，非常感谢，把判空代码注掉后就没问题了。奔溃的地方确实是因为第二级条目下没有child数据造成的！但我发现点击这个二级条目仍然会刷新其他的全部item,这里我做了个判断，如果没有下级item，不进行展开和折叠刷新条目。
    /**
     * 获得所有展开的childs,包括子item的childs
     *
     * @return
     */
    @Nullable
    private List<TreeItem> getExpandChild() {
        //下面的return不会返回null
        return ItemHelperFactory.getChildItemsWithType(this, TreeRecyclerType.SHOW_EXPAND);
    }
    /**
     * 展开
     */
    protected void onExpand() {
        isExpand = true;
        ItemManager itemManager = getItemManager();
        if (itemManager != null) {
            int itemPosition = itemManager.getItemPosition(this);
            List datas = itemManager.getAdapter().getDatas();
//          datas.addAll(itemPosition + 1, getExpandChild());
//          itemManager.notifyDataChanged();
            List<TreeItem> expandChild = getExpandChild();
            if (expandChild.size()>0) {
                datas.addAll(itemPosition + 1, expandChild);
                itemManager.notifyDataChanged();
            }

        }
    }

    /**
     * 折叠
     */
    protected void onCollapse() {
        isExpand = false;
        ItemManager itemManager = getItemManager();
        if (itemManager != null) {
            List datas = itemManager.getAdapter().getDatas();
//          datas.addAll(itemPosition + 1, getExpandChild());
//          itemManager.notifyDataChanged();
            List<TreeItem> expandChild = getExpandChild();
            if (expandChild.size()>0) {
                datas.removeAll(expandChild);
                itemManager.notifyDataChanged();
            }
        }
    }

**Comment by Jlanglang** [comment]
@StarSpark 
参考demo里的第一个例子，创建TreeRecyclerView的时候传入Type，TreeRecyclerType.SHOW_EXPAND

然后
   //创建item
                List<TreeItem> items = ItemHelperFactory.createItems(cityBeen, null);
                //遍历设置展开状态
                for (TreeItem item : items) {
                    if (item instanceof TreeItemGroup) {
                        ((TreeItemGroup) item).setExpand(true);
                    }
                }

这样默认就是展开的。

**Comment by StarSpark** [comment]
ok，谢谢
