### ISSUE TITLE
我想要默认三级都展开，但一级不可点击，可以加上这样的需求吗 

### ISSUE THREAD

**Issue by SanChunAndrroid** [Jlanglang/TreeRecyclerView#17]
我想要默认三级展开，一级不可点击，可以加上这样的需求吗

**Comment by Jlanglang** [comment]
可以复写onExpand实现,或者拦截掉onInterceptClick

**Comment by Jlanglang** [comment]
> 我想要三种三级展开，一级不可点击，可以加上这样的需求吗

复写onclick也可以应该
