### ISSUE TITLE
可不可以实现：第一第二级默认展开，一级不可以点击，点击二级打开第三级？

### ISSUE THREAD

**Issue by Wuqiusen** [Jlanglang/TreeRecyclerView#18]

**Comment by Jlanglang** [comment]
> _没有提供描述。_

你可以直接复写第一级的onClick,不带super,就不会展开了

**Comment by Wuqiusen** [comment]
主要是怎me让二级菜单默认打开；
我仿照ProvinceItem复写CountyItem里面的initChild发现报错，提示TreeItemGroup转换异常
public List<TreeItem> initChild(ProvinceBean.CityBean data) {
        List<TreeItem> items = ItemHelperFactory.createItems(data.areas, this);
        for (int i = 0; i < items.size(); i++) {
            TreeItemGroup treeItem = (TreeItemGroup) items.get(i);
            treeItem.setExpand(true);
        }

        return items;
    }

**Comment by Wuqiusen** [comment]
主要是怎me让二级菜单默认打开；
我仿照ProvinceItem复写CountyItem里面的initChild发现报错，提示TreeItemGroup转换异常
public List<TreeItem> initChild(ProvinceBean.CityBean data) {
        List<TreeItem> items = ItemHelperFactory.createItems(data.areas, this);
        for (int i = 0; i < items.size(); i++) {
            TreeItemGroup treeItem = (TreeItemGroup) items.get(i);
            treeItem.setExpand(true);
        }
        return items;
    }

**Comment by Jlanglang** [comment]
> 主要是怎me让二级菜单默认打开；
> 我仿照ProvinceItem复写CountyItem里面的initChild发现报错，提示TreeItemGroup转换异常
> public List initChild(ProvinceBean.CityBean data) {
> List items = ItemHelperFactory.createItems(data.areas, this);
> for (int i = 0; i < items.size(); i++) {
> TreeItemGroup treeItem = (TreeItemGroup) items.get(i);
> treeItem.setExpand(true);
> }
> 
> ```
>     return items;
> }
> ```

转换异常是因为data.areas映射的不是TreeItemGroup吧.

**Comment by Wuqiusen** [comment]
@TreeDataType(iClass = CountyItem.class)
    public static class CityBean {
这里都没改应该没有问题吧？找了很久没发现哪出现问题

**Comment by Jlanglang** [comment]
> > 主要是怎me让二级菜单默认打开；
> > 我仿照ProvinceItem复写CountyItem里面的initChild发现报错，提示TreeItemGroup转换异常
> > public List initChild(ProvinceBean.CityBean data) {
> > List items = ItemHelperFactory.createItems(data.areas, this);
> > for (int i = 0; i < items.size(); i++) {
> > TreeItemGroup treeItem = (TreeItemGroup) items.get(i);
> > treeItem.setExpand(true);
> > }
> > ```
> >     return items;
> > }
> > ```
> 
> 转换异常是因为data.areas映射的不是TreeItemGroup吧.

 @TreeDataType(iClass = AreaItem.class)
        public static class AreasBean {
            /**
             * areaId : 2799
             * areaName : 三环以内
             */

            public int areaId;
            public String areaName;
        }

AreasBean 是TreeItem

**Comment by Jlanglang** [comment]
> > > 主要是怎me让二级菜单默认打开；
> > > 我仿照ProvinceItem复写CountyItem里面的initChild发现报错，提示TreeItemGroup转换异常
> > > public List initChild(ProvinceBean.CityBean data) {
> > > List items = ItemHelperFactory.createItems(data.areas, this);
> > > for (int i = 0; i < items.size(); i++) {
> > > TreeItemGroup treeItem = (TreeItemGroup) items.get(i);
> > > treeItem.setExpand(true);
> > > }
> > > ```
> > >     return items;
> > > }
> > > ```
> > 
> > 
> > 转换异常是因为data.areas映射的不是TreeItemGroup吧.
> 
> @TreeDataType(iClass = AreaItem.class)
> public static class AreasBean {
> /**
> * areaId : 2799
> * areaName : 三环以内
> */
> 
> ```
>         public int areaId;
>         public String areaName;
>     }
> ```
> 
> AreasBean 是TreeItem

你要2级默认展开,应该去1级里面设置..

**Comment by Wuqiusen** [comment]
嗯嗯，我也发现问题了，谢谢，我再试试
