### ISSUE TITLE
点击事件怎么设置？

### ISSUE THREAD

**Issue by liuxia0017** [Jlanglang/TreeRecyclerView#2]
BaseItem 里的onClick方法吗？BaseItem这个类又怎么用呢

**Comment by Jlanglang** [comment]
嗯,Baseitem的onclick方法,子类复写就好了
adapter是以Baseitem为基本单位的.

demo里有详细的用法,每个Baseitem的子类都是一种条目样式.操作的逻辑也在BaseItem里面.你可以把Baseitem理解为MVP中的P.
