### ISSUE TITLE
大佬好，我在三级item中遇到一个问题

### ISSUE THREAD

**Issue by ccy01** [Jlanglang/TreeRecyclerView#21]
在三级item，如父item，子item，孙item，当三个item都展开时，在点击父item关闭展开，在点击父item展开，然后孙item会数量加倍，这个怎么解决。

**Comment by Jlanglang** [comment]
最新的版本应该已经修复这个问题了

**Comment by Jlanglang** [comment]
> 在三级item，如父item，子item，孙item，当三个item都展开时，在点击父item关闭展开，在点击父item展开，然后孙item会数量加倍，这个怎么解决。

版本是1.3.1.1吗

**Comment by ccy01** [comment]
哦哦，我用的com.github.Jlanglang:TreeRecyclerView:1.3.0 这个 原来新版修好了，感谢大佬 
 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jlanglang"<notifications@github.com&gt;; 
发送时间: 2020年3月11日(星期三) 下午5:42
收件人: "Jlanglang/TreeRecyclerView"<TreeRecyclerView@noreply.github.com&gt;; 
抄送: "我爱学习"<965402719@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Jlanglang/TreeRecyclerView] 大佬好，我在三级item中遇到一个问题 (#21)



 
在三级item，如父item，子item，孙item，当三个item都展开时，在点击父item关闭展开，在点击父item展开，然后孙item会数量加倍，这个怎么解决。
  
版本是1.3.1.1吗

**Comment by ccy01** [comment]
后面用了implementation 'com.github.Jlanglang:TreeRecyclerView:1.3.1.1'  后 好像还是没好。 
 



------------------ 原始邮件 ------------------
发件人: "Jlanglang"<notifications@github.com&gt;; 
发送时间: 2020年3月11日(星期三) 下午5:42
收件人: "Jlanglang/TreeRecyclerView"<TreeRecyclerView@noreply.github.com&gt;; 
抄送: "我爱学习"<965402719@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Jlanglang/TreeRecyclerView] 大佬好，我在三级item中遇到一个问题 (#21)



 
在三级item，如父item，子item，孙item，当三个item都展开时，在点击父item关闭展开，在点击父item展开，然后孙item会数量加倍，这个怎么解决。
  
版本是1.3.1.1吗

**Comment by Jlanglang** [comment]
> 后面用了implementation 'com.github.Jlanglang:TreeRecyclerView:1.3.1.1' 后 好像还是没好。
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "Jlanglang"<notifications@github.com&gt;; 发送时间: 2020年3月11日(星期三) 下午5:42 收件人: "Jlanglang/TreeRecyclerView"<TreeRecyclerView@noreply.github.com&gt;; 抄送: "我爱学习"<965402719@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [Jlanglang/TreeRecyclerView] 大佬好，我在三级item中遇到一个问题 (#21) 在三级item，如父item，子item，孙item，当三个item都展开时，在点击父item关闭展开，在点击父item展开，然后孙item会数量加倍，这个怎么解决。 版本是1.3.1.1吗 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

demo是否有这个问题
