### ISSUE TITLE
混淆问题

### ISSUE THREAD

**Issue by samgsmg** [Jlanglang/TreeRecyclerView#22]
混淆时需要加入这些
-keep class * extends com.baozi.treerecyclerview.*{*;}
-keep class * extends com.baozi.treerecyclerview.item.*{*;}
-keep class com.baozi.treerecyclerview.*{*;}

extend TreeItem 的 类，需要定义 一个不带参数的 constructor. 
否则展示不出来。

**Comment by Jlanglang** [comment]
> 混淆时需要加入这些
> -keep class * extends com.baozi.treerecyclerview._{_;}
> -keep class * extends com.baozi.treerecyclerview.item._{_;}
> -keep class com.baozi.treerecyclerview._{_;}
> 
> extend TreeItem 的 类，需要定义 一个不带参数的 constructor.
> 否则展示不出来。
异常可否发一下

**Comment by samgsmg** [comment]
表现就是展示不出，异常当时没有抓出来，可以试一下混淆的情况。

**Comment by Carymax1988** [comment]
自定义item也要注意不要混淆，跟源码发现

**Comment by Carymax1988** [comment]
混淆之后，这里（Field field = aClass.getField(key);）报异常java.lang.NoSuchFieldException: 
因为混淆后类名编程com.xxx.b.c，这样的格式，注解找不到

**Comment by Jlanglang** [comment]
>  表现就是展示不出，异常当时没有抓出来，可以试一下混淆的情况。

-keep public class * extends  com.baozi.treerecyclerview.item.TreeItem {}
-keep public class * extends android.support.annotation.**

需要加上这两句,是我漏掉了

**Comment by Jlanglang** [comment]
> 混淆之后，这里（Field field = aClass.getField(key);）报异常java.lang.NoSuchFieldException:
> 因为混淆后类名编程com.xxx.b.c，这样的格式，注解找不到

-keep public class * extends  com.baozi.treerecyclerview.item.TreeItem {}
-keep public class * extends android.support.annotation.**

需要加上这两句,是我漏掉了

**Comment by Jlanglang** [comment]
此iss可以关了 ,嘿嘿
