### ISSUE TITLE
刷新问题

### ISSUE THREAD

**Issue by caiyaoyao** [Jlanglang/TreeRecyclerView#23]
当我在onBindViewHolder 中调用 getItemManager().notifyDataChanged()刷新出现 Cannot call this method while RecyclerView is computing a layout or scrolling androidx.recyclerview.widget.RecyclerView错误

**Comment by Jlanglang** [comment]
> 当我在onBindViewHolder 中调用 getItemManager().notifyDataChanged()刷新出现 Cannot call this method while RecyclerView is computing a layout or scrolling androidx.recyclerview.widget.RecyclerView错误

 你怎么会想到在onBindViewHolder里面去调用刷新,这不就递归死循环了么....

**Comment by caiyaoyao** [comment]
> > 当我在onBindViewHolder 中调用 getItemManager().notifyDataChanged()刷新出现 Cannot call this method while RecyclerView is computing a layout or scrolling androidx.recyclerview.widget.RecyclerView错误
> 
> 你怎么会想到在onBindViewHolder里面去调用刷新,这不就递归死循环了么....
recyclerview 中的checkbox 点击后怎么刷新了
