### ISSUE TITLE
点击最后一个一级菜单，展开子菜单，屏幕不会上移以显示展开的子菜单

### ISSUE THREAD

**Issue by wawo00** [Jlanglang/TreeRecyclerView#25]
可以看下demo中 三级城市-钓鱼岛，点击钓鱼岛，屏幕没有进行滑动操作以显示展开的子菜单

**Comment by Jlanglang** [comment]
这个rv属于自身的特性，有需要可以手动设置一下。

**Comment by Jlanglang** [comment]
> 可以看下demo中 三级城市-钓鱼岛，点击钓鱼岛，屏幕没有进行滑动操作以显示展开的子菜单

这个rv属于自身的特性，有需要可以手动设置一下。
