### ISSUE TITLE
是否支持多类型？

### ISSUE THREAD

**Issue by LiarrDev** [Jlanglang/TreeRecyclerView#26]
我想在 `TreeItemGroup` 或者 `TreeItem` 中使用 ViewType，添加 Header 和 Footer，但没找到相关的方法

**Comment by Jlanglang** [comment]
> 我想在 `TreeItemGroup` 或者 `TreeItem` 中使用 ViewType，添加 Header 和 Footer，但没找到相关的方法

支持的,你可以看看news目录,有添加foot,

实际上可以随意拼接.都是TreeItem
