### ISSUE TITLE
在不需要使用多级功能的地方，能否使用该库？

### ISSUE THREAD

**Issue by LiarrDev** [Jlanglang/TreeRecyclerView#27]
如题，假如我不需要用到多级功能，是否可以直接封装成 TreeItem 传进去？

我尝试了这种方式，代码如下：

```Java
@TreeDataType(iClass = AccountItem.class)
public class Account  {}

public class AccountItem extends TreeItem<Account> {}

public class AccountFragment extends Fragment {
    private final TreeRecyclerAdapter adapter = new TreeRecyclerAdapter();
    LinearLayoutManager manager = new LinearLayoutManager(requireContext());
    recyclerView.setLayoutManager(manager);
    ...
    private void notifyList(List<Account> list) {
        List<TreeItem> items = ItemHelperFactory.createItems(list);
        adapter.getItemManager().replaceAllItem(items);
    }
}
```

似乎没办法正常显示

**Comment by Jlanglang** [comment]
> 如题，假如我不需要用到多级功能，是否可以直接封装成 TreeItem 传进去？
> 
> 我尝试了这种方式，代码如下：
> 
> ```java
> @TreeDataType(iClass = AccountItem.class)
> public class Account  {}
> 
> public class AccountItem extends TreeItem<Account> {}
> 
> public class AccountFragment extends Fragment {
>     private final TreeRecyclerAdapter adapter = new TreeRecyclerAdapter();
>     LinearLayoutManager manager = new LinearLayoutManager(requireContext());
>     recyclerView.setLayoutManager(manager);
>     ...
>     private void notifyList(List<Account> list) {
>         List<TreeItem> items = ItemHelperFactory.createItems(list);
>         adapter.getItemManager().replaceAllItem(items);
>     }
> }
> ```
> 
> 似乎没办法正常显示

可以的,参考下demo中的mine和tbhome

> 

注意notify更新在主线程

**Comment by LiarrDev** [comment]
> > 如题，假如我不需要用到多级功能，是否可以直接封装成 TreeItem 传进去？
> > 我尝试了这种方式，代码如下：
> > ```java
> > @TreeDataType(iClass = AccountItem.class)
> > public class Account  {}
> > 
> > public class AccountItem extends TreeItem<Account> {}
> > 
> > public class AccountFragment extends Fragment {
> >     private final TreeRecyclerAdapter adapter = new TreeRecyclerAdapter();
> >     LinearLayoutManager manager = new LinearLayoutManager(requireContext());
> >     recyclerView.setLayoutManager(manager);
> >     ...
> >     private void notifyList(List<Account> list) {
> >         List<TreeItem> items = ItemHelperFactory.createItems(list);
> >         adapter.getItemManager().replaceAllItem(items);
> >     }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 似乎没办法正常显示
> 
> 可以的,参考下demo中的mine和tbhome
> 
> > 
> 
> 注意notify更新在主线程

好的，感谢
