### ISSUE TITLE
发现两个问题

### ISSUE THREAD

**Issue by blazeqin** [Jlanglang/TreeRecyclerView#6]
侧滑view的显示与隐藏不稳定，尤其是按住父view滑动时最明显；子view的排序问题，表层数据改变了，底部数据添加一条直接加在最后

**Comment by Jlanglang** [comment]
侧滑的话,只要滚动就会默认隐藏,而不会保留

排序的话,对于指定某个父item插入更新可能有问题,,有待优化.

你可以说的再具体点吗.用的哪一种item.或者直接贴代码出来

**Comment by blazeqin** [comment]
比如右边侧滑，删除一条子view后会随机滑开另一个子view

**Comment by blazeqin** [comment]
TreeRecyclerAdapter里的内部类TreeItemManageImpl，有个additem的方法， getDatas().add(position, item)这里插入的时候是正确的位置，所以显示的没有问题。接着用了add(item)，这个时候并没有添加到正确的位置。因为我要实现子view的移动，所以就出了问题。
我在treeitem里添加了一个字段position，记录子view在父view的位置，修改的时候更新这个字段。

**Comment by blazeqin** [comment]
ItemHelperFactory并不是通用的，只适合三级使用，其他层级使用时，getChildItemsWithType这个方法会有问题，导致TreeRecyclerType这个type并不能正确显示，而且isExpand这个字段忘记更新了

**Comment by blazeqin** [comment]
侧滑的问题还没解决，有两个问题：1.打开与关闭容易混乱，主要是滑动关闭不完全 2.侧滑菜单的操作并不影响打开与关闭的逻辑，所以造成一个问题，删除一个子view仍然有一个view被滑开。

**Comment by Jlanglang** [comment]
已了解，感谢，会尽快修改😀

**Comment by blazeqin** [comment]
swipeLayout的close和open虽然有自己的一些问题，比如有人解决了 abnormal offset （https://github.com/daimajia/AndroidSwipeLayout/pull/483/files）；有个问题应该是这边封装的问题，就是当一个子view展开后，展开另外一个父类时，刚刚展开的子view close，但是会有其他的子view open。还是我之前提的两个问题：第一个问题是swipeLayout自身的问题，第二个问题是封装的问题
