### ISSUE TITLE
点击事件问题

### ISSUE THREAD

**Issue by singsoul** [Jlanglang/TreeRecyclerView#7]
我发现接口回调的点击事件，只支持最后一级的item，假如他是123级的item，部分有3级部分只有2级，我点2级的时候怎么获取点击事件呢

**Comment by Jlanglang** [comment]
确实在设计的时候，TreeGroupItem如果可以展开的话，默认点击是展开，而不是点击回调。如果是不可展开，点击就会是点击回调

**Comment by singsoul** [comment]
我现在就是2级跟3级的单独做处理，判断他们是否能展开，来决定怎么返回
